# Generated by Django 3.0.1 on 2020-01-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaing',
            name='category',
            field=models.IntegerField(default=0),
        ),
    ]
