# Generated by Django 3.0.1 on 2020-01-09 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_campaing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorycampaing',
            name='campaing',
        ),
        migrations.AlterField(
            model_name='campaing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CategoryCampaing'),
        ),
    ]
